plugins {
    id 'java'
    id 'java-library'
    id 'idea'
    id 'xyz.wagyourtail.unimined' version '1.4.36-kappa'
}

version = gradle.ext.nextVersion
group = 'com.igteam.immersivegeology'

base {
    archivesName = 'ImmersiveGeology'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    modCompileOnly
    compileOnly.extendsFrom(modCompileOnly)
    modRuntimeOnly
    runtimeOnly.extendsFrom(modRuntimeOnly)
}

unimined.minecraft {
    version version_minecraft

    mappings {
        mcp('stable', '39-1.12')
    }

    cleanroom {
        loader version_cleanroom
        runs.all {
            args += ['--username', minecraft_username]
            systemProperty('ig.debugMultiblockFormation', 'true')
            workingDir = project.file('run1122')
            return
        }
    }

    defaultRemapJar = false
    remap(tasks.named('jar').get())

    mods {
        remap(configurations.modCompileOnly)
        remap(configurations.modRuntimeOnly)
    }
}

repositories {
    maven { name = 'CleanroomMC'; url = 'https://maven.cleanroommc.com' }
    maven { name = 'CurseMaven'; url = 'https://cursemaven.com' }
    maven { name = 'CleanroomCurseMaven'; url = 'https://curse.cleanroommc.com' }
    maven { name = 'Modrinth'; url = 'https://api.modrinth.com/maven' }
    mavenCentral()
    mavenLocal()
}

dependencies {
    modImplementation "curse.maven:immersive-engineering-${curse_ie_project}:${curse_ie_file}"
    modImplementation "curse.maven:engineered-schematics-1207780:8799257"
    modImplementation "curse.maven:immersive-intelligence-344344:8933879"
    modImplementation "curse.maven:jei-238222:8752694"
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', version_minecraft

    filesMatching('mcmod.info') {
        expand 'version': project.version, 'mcversion': version_minecraft
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-Xmaxerrs' << '2000'
}

jar {
    manifest {
        attributes([
                'Specification-Title'   : mod_name,
                'Specification-Vendor'  : mod_authors,
                'Specification-Version' : project.version,
                'Implementation-Title'  : mod_name,
                'Implementation-Version': project.version,
                'Implementation-Vendor' : mod_authors
        ])
    }
}

