# @file mods.toml
# @spec TOML v0.5.0 (https://github.com/toml-lang/toml)
#
modLoader="javafml"
loaderVersion="[25,)"
license="Blu's License of Common Sense"

[[mods]]
modId = "immersivegeology"
version = "${version}"
displayName = "Immersive Geology"
description = "An updated version of Immersive Geology, tailored for HardRock TerraFirmaCraft"
authors = "muddykat-tech, UnSchtalch, Robota"
displayURL = "https://minecraft.curseforge.com/projects/immersive-geology/"
logoFile = "logo.png"
credits = "All the great other Git Contributors"

[[dependencies.immersivegeology]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.immersivegeology]]
modId="minecraft"
mandatory=true
versionRange="[${mc_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.immersivegeology]]
modId="jei"
mandatory=false
versionRange="[${jei_version},)"
ordering="NONE"
side="BOTH"