modLoader="javafml"
loaderVersion="[36,)"
logoFile="logo.png"
logoBlur=false
issueTrackerURL=""
license="LGPL v2.1"

[[mods]]
modId="immersive_geology"
updateJSONURL=""
version="Beta v1.3 MC 1.16.5"
displayName="Immersive Geology"
displayURL="https://www.curseforge.com/minecraft/mc-mods/immersive-geology"
credits='''
Codework done by Muddykat and UnSchtalch assisted by Kuruma
Recipe Research done by UnSchtalch
Modelwork done by UnSchtalch assisted by Muddykat
Texturework done by SteelBlue8 (Ingame); Muddykat, Kuruma and UnSchtalch (Machine Gui's)
Balance Tweaking by UnSchtalch
Manual Information filled out by Muddykat
Early Frameworking by Kuruma, UnSchtalch and Pablio8

Special Thanks to Sen#1629 for the Chemical Vat Model
'''
authors="Muddykat, UnSchtalch, SteelBlue8, Kuruma, JStocke, Pabilo8"
description='''
Immersive Implementation of Minerals and ore processing! We add a bunch of minerals, ores and metals.
You're gonna need JEI.
'''

[[dependencies.immersive_geology]]
    modId="immersiveengineering"
    mandatory=true
    versionRange="[1.16.5-5.1.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.immersive_geology]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.immersive_geology]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"