# @file mods.toml
# @spec TOML v0.5.0 (https://github.com/toml-lang/toml)
#
modLoader="javafml"
loaderVersion="[25,)"
license="LGPL-3.0"

[[mods]]
modId = "immersivegeology"
version = "${version}-${build_number}"
displayName = "Immersive Geology"
description = "An updated in development version of Immersive Geology, tailored for HardRock TerraFirmaCraft."
authors = "muddykat-tech, UnSchtalch and Crimson Twilight"
displayURL = "https://minecraft.curseforge.com/projects/immersive-geology/"
logoFile = "logo.png"
credits = '''
Robota and UnSchtalch for the amazing Multiblock Models!
Special thanks to Steelblue8 for the some of the lovely Item and Block Textures.
Thanks again to UnSchtalch, Robota and Crimson Twilight for the Multiblock Textures
'''

[[dependencies.immersivegeology]]
modId="forge"
mandatory=true
versionRange="[47.1.54,)"
ordering="NONE"
side="BOTH"

[[dependencies.immersivegeology]]
modId="minecraft"
mandatory=true
versionRange="[${mc_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.immersivegeology]]
modId="jei"
mandatory=false
versionRange="[${jei_version},)"
ordering="NONE"
side="BOTH"