# @file mods.toml
# @spec TOML v0.5.0 (https://github.com/toml-lang/toml)
#
modLoader="javafml"
loaderVersion="[25,)"
license="LGPL-3.0"

[[mods]]
modId = "immersivegeology"
version = "${version}"
displayName = "Immersive Geology"
description = '''
An updated in development version of Immersive Geology.

- Big thanks to Steelblue8 for the beautiful item and block textures.
- Special thanks to Peter and UnSchtalch for the fantastic multiblock models.
- Appreciation to UnSchtalch, Peter, and Crimson Twilight for their excellent work on the multiblock textures.
- Additional thanks to Peter for creating new item textures.
'''
authors = "Muddykat-Tech and UnSchtalch"
displayURL = "https://minecraft.curseforge.com/projects/immersive-geology/"
logoFile = "logo.png"
credits = "Crimson Twilight, Peter, RGBoid"
[[dependencies.immersivegeology]]
modId="forge"
mandatory=true
versionRange="[47.1.54,)"
ordering="AFTER"
side="BOTH"

[[dependencies.immersivegeology]]
modId="minecraft"
mandatory=true
versionRange="[${mc_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.immersivegeology]]
modId="immersiveengineering"
mandatory=true
versionRange="[${version_ie},]"
ordering="NONE"
side="BOTH"

[[dependencies.immersivegeology]]
modId="jei"
mandatory=false
versionRange="[${jei_version},)"
ordering="NONE"
side="BOTH"