modLoader="javafml"
loaderVersion="[36,)"
logoFile="logo.png"
logoBlur=false
issueTrackerURL=""
license="LGPL v2.1"

[[mods]]
modId="immersive_geology"
updateJSONURL=""
version="0.92v16"
displayName="Immersive Geology"
displayURL=""
credits="Muddykat, JStocke, Kuruma, Pabilo8, UnSchtalch"
authors="Muddykat, JStocke, Kuruma, Pabilo8, UnSchtalch"
description='''
Many Rocks, Many Metals, Many things
'''

[[dependencies.immersive_geology]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.27,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.immersive_geology]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"