name: Feature Suggestion
description: If you have an idea or feature to add to Immersive Geology
title: "[Suggestion] ... "
labels: ["suggestion :bulb:"]
body:
  - type: markdown
    attributes:
      value: |
        You have an idea or feature you would love to see ingame? That's awesome, we love hearing those!
        
        Please check first if we don't already have it in IG. A lot of the suggestions we get are already in the mod.
        Additionally, a good few open requests are on this tracker, so use the search function to avoid duplicates.

  - type: textarea
    id: idea
    attributes:
      label: Explain your idea
      description: |
        The things we look for in suggestions, in a rough order of priority:
        1) Useful gameplay feature
        2) Can be visually interesting (we love when things look cool!)
        3) Is viable to implement (this is hard to judge, I know!)
        
        Bonus points if it ties into IG's existing machines, tech-tree and established recipes!
    validations:
      required: true
