/*
 * Muddykat
 * Copyright (c) 2025
 *
 * This code is licensed under "GNU LESSER GENERAL PUBLIC LICENSE"
 * Details can be found in the license file in the root folder of this project
 */

package com.igteam.immersivegeology.common.world.compat;

import com.igteam.immersivegeology.common.config.IGServerConfig;
import com.igteam.immersivegeology.core.material.GeologyMaterial;
import com.igteam.immersivegeology.core.material.data.enums.StoneEnum;
import com.igteam.immersivegeology.core.material.helper.flags.ModFlags;
import com.igteam.immersivegeology.core.material.helper.material.StoneFormation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.Level;

import java.util.Arrays;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * What Immersive Geology needs to know about a TerraFirmaCraft world.
 * <p>
 * TFC replaces the overworld's stone wholesale with its own rock types, which cover the igneous, metamorphic and
 * sedimentary formations rather than {@link StoneFormation#MINECRAFT_STONE}. That changes which materials the
 * overworld can host: several minerals accept those formations but not Minecraft stone, and so are pinned to the
 * Nether by their dimension whitelist even though a TFC overworld is full of rock that would take them.
 * <p>
 * Everything here is soft compat - TerraFirmaCraft is never a compile or load time dependency, so the world type
 * is identified by the chunk generator's registry name rather than by any TFC class.
 */
public final class IGTFCWorld
{
	private IGTFCWorld()
	{
	}

	private static final String TFC_NAMESPACE = "tfc";
	private static volatile Set<StoneFormation> formations;

	/**
	 * True when this level's terrain is generated by TerraFirmaCraft.
	 */
	public static boolean isTFCWorld(ServerLevel level)
	{
		if(!ModFlags.TFC.isStrictlyLoaded()) return false;
		return level.getChunkSource().getGenerator().getTypeNameForDataFixer()
				.map(key -> TFC_NAMESPACE.equals(key.location().getNamespace()))
				.orElse(false);
	}

	/**
	 * Whether {@code allow_all_in_overworld} is in force here: the config is on, and this really is a TFC world.
	 * When it is, a material may generate in the overworld regardless of its dimension whitelist, provided
	 * {@link #canHostInOverworld} agrees the rock can take it.
	 */
	public static boolean overridesDimensionWhitelist(ServerLevel level)
	{
		return IGServerConfig.TFC.allow_all_in_overworld.get()&&isTFCWorld(level);
	}

	/** Whether TFC's rock types cover any stone formation this material accepts. */
	public static boolean canHostInOverworld(GeologyMaterial material)
	{
		for(StoneFormation formation : stoneFormations())
		{
			if(material.isValidStoneFormation(formation)) return true;
		}
		return false;
	}

	/** Every stone formation TFC's rock types cover, derived from the stone list rather than hardcoded. */
	public static Set<StoneFormation> stoneFormations()
	{
		Set<StoneFormation> cached = formations;
		if(cached==null)
		{
			cached = Arrays.stream(StoneEnum.values())
					.filter(stone -> stone.hasFlag(ModFlags.TFC)&&stone.isStoneTypeValid())
					.map(stone -> stone.instance().getStoneFormation())
					.collect(Collectors.toUnmodifiableSet());
			formations = cached;
		}
		return cached;
	}

	public static boolean isOverworld(Level level)
	{
		return Level.OVERWORLD.equals(level.dimension());
	}
}
