name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  notify-discord:
    continue-on-error: true
    name: Notify Discord
    runs-on: ubuntu-latest
    concurrency:
      group: discord
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Notify Discord
        env:
          COMMIT_FROM: ${{ github.event.before }}
          COMMIT_TO: ${{ github.event.after }}
          WEBHOOK: ${{ secrets.WH_PUSH_PUBLIC }}
          REPO: ${{ github.repository }}
          REPO_NAME: ${{ github.event.repository.custom_properties.project_pretty_name }}
        run: cd ./.github/workflows/ ; chmod +rx discord_commit.sh ; bash discord_commit.sh -i