name: Pull Request
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  notify-discord:
    runs-on: ubuntu-latest
    name: Notify Discord
    steps:
      - name: Notify Internal Discord
        uses: sebastianpopp/discord-action@releases/v2
        with:
          token: ${{ secrets.OPTIMIZATION_TOKEN }}
          webhook: ${{ secrets.WH_PR_PUBLIC }}
          message: "[@${{ github.event.pull_request.user.login }}](<https://github.com/${{ github.event.pull_request.user.login }}>) has contributed to Engineers' Cause with [${{ github.event.issue.title }}](<https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}>)."